#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6451350376                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : th                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/om/app/toeic-vocabulary/id6451350376 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.eswizardry.toeic_vocabulary                                         # Enter Google Play Store URL.
presskit_download_link                    : #assets/your_press_kit.zip                # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : TOEIC Vocabulary - Word Builder           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Introducing TOEIC Vocabulary-Word Builder, your ultimate passport to TOEIC success! With a robust collection of over 1000+ hand-picked words, this app will propel your vocabulary skills to new heights. Immerse yourself in an interactive learning experience packed with engaging games that challenge your memory, listening comprehension, and vocabulary writing prowess. Get ready to embark on an exhilarating journey of word mastery!
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Bancha Rajainthong
your_link                                 : https://eswizardry.github.io/
your_city                                 : Nong Bua Lam Phu
email_address                             : eswizardry@gmail.com
facebook_username                         :
instagram_username                        : eswizardry
twitter_username                          : eswizardry
github_username                           : eswizardry
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Flashcard
    description                           : Let's learn English with beautiful flashcards and sounds! 1000+ words! Unlock the power of language with our extensive word bank spanning various themes and contexts. From business and finance to travel and technology, we've got you covered.
    fontawesome_icon_name                 : bolt

  - title                                 : Spaced Repetition Algorithm
    description                           : Accelerate your learning with our intelligent Spaced Repetition Algorithm. It optimizes the review process by presenting words at strategic intervals, ensuring maximum retention. With each review session, you'll reinforce your knowledge and strengthen your long-term memory, making vocabulary recall effortless.
    fontawesome_icon_name                 : space-shuttle

  - title                                 : Sharpen Listening Skills
    description                           : Train your ears to catch every nuance with our listening exercises. Tune in to authentic TOEIC-style audio recordings and answer questions to sharpen your listening comprehension.
    fontawesome_icon_name                 : headphones

  - title                                 : Track Your Progress
    description                           : Stay motivated and monitor your progress with detailed statistics and performance insights. Keep tabs on your strengths and areas for improvement, allowing you to tailor your study sessions accordingly. Witness your growth over time and celebrate your milestones on the path to TOEIC success.
    fontawesome_icon_name                 : tasks

  - title                                 : Engaging Learning Games
    description                           : Learning doesn't have to be boring! Put your skills to the test through exciting games that make vocabulary acquisition fun and addictive.
    fontawesome_icon_name                 : gamepad

  - title                                 : Enhance Writing Proficiency
    description                           : Develop your writing skills by practicing with a wide range of vocabulary. Our writing exercises allow you to express yourself using newly acquired words.
    fontawesome_icon_name                 : pencil-square-o

  - title                                 : #Easy to use
    description                           : #The App easy and safe to use by selecting a category to review flashcards.
    fontawesome_icon_name                 : #star

  - title                                 : #FontAwesome Support
    description                           : #Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/cover.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : purple                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
